<a href="https://colab.research.google.com/github/AIceDog/Pyotrch-Notes/blob/master/Pytorch_bmm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
#We will take two matrices of 3 dimensional size which are to be multiplied
m1 = torch.randn(2, 3, 3)
m2 = torch.randn(2, 3, 4)
print("1st input matrix - \n",m1)
print("\n2nd input matrix - \n",m2)
print("\nResultant output matrix - \n",torch.bmm(m1,m2))

First input matrix - 
 tensor([[[-1.1108, -0.4713,  0.2567],
         [-1.9131,  0.4476, -1.9099],
         [ 1.4592, -0.8361,  0.6711]],

        [[-1.3722,  0.3043,  0.5788],
         [-0.4712,  0.8222,  0.6162],
         [-0.9875, -1.2292, -0.5379]]])

Second input matrix - 
 tensor([[[ 1.7958, -0.1196, -0.7332, -0.8894],
         [ 0.3633,  0.4796,  0.5263,  1.3257],
         [ 1.4008,  0.5024,  1.3178,  0.7504]],

        [[ 1.1753, -1.7787, -1.0606, -0.3914],
         [ 0.1616, -0.3574, -0.0459, -0.2158],
         [ 0.5126,  0.3174, -0.0770,  0.1901]]])

Resultant output matrix - 
 tensor([[[-1.8064,  0.0358,  0.9047,  0.5559],
         [-5.9484, -0.5159, -0.8786,  0.8618],
         [ 3.2568, -0.2384, -0.6255, -1.9026]],

        [[-1.2670,  2.5158,  1.3969,  0.5815],
         [-0.1052,  0.7399,  0.4146,  0.1242],
         [-1.6349,  2.0250,  1.1452,  0.5495]]])


In [9]:
m11 = m1[0]
m21 = m2[0]
print("1st sub matrix of m1 - \n", m11)
print("\n1st sub matrix of m2 - \n", m21)
print("\nResultant output matrix of m11 * m21 - \n", torch.mm(m11, m21))

1st sub matrix of m1 - 
 tensor([[-1.1108, -0.4713,  0.2567],
        [-1.9131,  0.4476, -1.9099],
        [ 1.4592, -0.8361,  0.6711]])

1st sub matrix of m2 - 
 tensor([[ 1.7958, -0.1196, -0.7332, -0.8894],
        [ 0.3633,  0.4796,  0.5263,  1.3257],
        [ 1.4008,  0.5024,  1.3178,  0.7504]])

Resultant output matrix of m11 * m21 - 
 tensor([[-1.8064,  0.0358,  0.9047,  0.5559],
        [-5.9484, -0.5159, -0.8786,  0.8618],
        [ 3.2568, -0.2384, -0.6255, -1.9026]])


In [10]:
m12 = m1[1]
m22 = m2[1]
print("2nd sub matrix of m1 - \n", m12)
print("\n2nd sub matrix of m2 - \n", m22)
print("\nResultant output matrix of m12 * m22 - \n", torch.mm(m12, m22))

2nd sub matrix of m1 - 
 tensor([[-1.3722,  0.3043,  0.5788],
        [-0.4712,  0.8222,  0.6162],
        [-0.9875, -1.2292, -0.5379]])

2nd sub matrix of m2 - 
 tensor([[ 1.1753, -1.7787, -1.0606, -0.3914],
        [ 0.1616, -0.3574, -0.0459, -0.2158],
        [ 0.5126,  0.3174, -0.0770,  0.1901]])

Resultant output matrix of m12 * m22 - 
 tensor([[-1.2670,  2.5158,  1.3969,  0.5815],
        [-0.1052,  0.7399,  0.4146,  0.1242],
        [-1.6349,  2.0250,  1.1452,  0.5495]])
